### ISSUE TITLE
PaperMC downloads API v1 has been deprecated. Advisory to move to v2.

### ISSUE THREAD

**Issue by TheFlagCourier** [krusic22/Potato-Scripts#4]
As of November 24th, PaperMC released version 2 of its downloads API, deprecating version 1 and putting a notice out that directly accessing the CI publicly will be removed.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/2712890/101840821-6d09c280-3b0a-11eb-8e56-8d41c73a8345.png)

Source: The PaperMC Discord &mdash; [Invite](https://discord.gg/papermc) | [Message Link](https://discord.com/channels/289587909051416579/492517675680006144/780784931605184512)

</details>

[Documentation for Version 2](https://papermc.io/api/docs/)

**Comment by krusic22** [comment]
I know about the change, just wanted to wait for v2 to get latest build, but [this](https://github.com/PaperMC/bibliothek/issues/3#issuecomment-736136358) might, not be the case. 
I'm going to implement something tomorrow.

**Comment by krusic22** [comment]
Seems fine, going to push to Spigot some time later.
